site_name: Quarkonium
pages:
  - Welcome: index.md
  - About: about.md
  - BAO: bao.md
  - BAS: bas.md
  - DAP: dap.md
  - Whitepaper: whitepaper.md
  - POC:
    - VAST: 'poc/vast.md'
  - Misc: misc.md
theme: readthedocs

