site_name: Quarkonium
pages:
  - Home: index.md
  - About: about.md
  - BAO: bao.md
  - DAS: das.md
  - DAP: dap.md
  - BOT: bot.md
#   - Whitepaper: whitepaper.md
  - POC:
    - VAST: 'poc/vast.md'
    - III: 'poc/iii.md'
    - PDAMP: 'poc/pdamp.md'
    - Badge: 'poc/badge.md'
    - ABOT: 'poc/abot.md'
  - Misc: misc.md
theme: readthedocs

